---
- hosts: all
  vars:
  - base_packages:
    - vim-enhanced
  become: yes
  pre_tasks:
    - name: Create root SSH directory
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0750'
    - name: Insert Vagrant's insecure SSH private key
      copy:
        src: ~/.vagrant.d/insecure_private_key
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: '0400'
    - name: Copy Vagrant's authorized keys to root user
      copy:
        remote_src: yes
        src: /home/vagrant/.ssh/authorized_keys
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0755'
  roles:
  - base-packages

- hosts: client
  vars:
  - restraint_server: no
  become: yes
  roles:
  - restraint

- hosts:
  - test01
  - test02
  vars:
  - restraint_client: no
  become: yes
  roles:
  - restraint
  post_tasks:
    - name: Create Restraint tasks directory
      file:
        path: /usr/local/share/restraint-tasks
        state: directory
        owner: root
        group: vagrant
        mode: '0775'
    - name: List tasks
      find:
        paths: /vagrant/restraint-tasks/
        file_type: directory
        recurse: no
      register: restraint_tasks
    - name: Install Ansible archive dependencies
      package:
        name:
          - tar
          - gzip
        state: present
    - name: Pack Restraint tasks
      archive:
        path: "{{ item.path }}/*"
        dest: "/usr/local/share/restraint-tasks/{{ item.path.split('/')[-1] }}.tar.gz"
        format: gz
        force_archive: yes
      with_items: "{{ restraint_tasks.files }}"
