---
- include_tasks: repos.yml

- name: Install Restraint client
  package:
    name: "restraint-client{{ restraint_release_tag }}"
    state: latest
  tags:
  - restraint
  - packages

- name: Install Restraint client debugging packages
  package:
    name:
    - "restraint-client-debuginfo{{ restraint_release_tag }}"
    - valgrind
    state: latest
  when: restraint_debug
  tags:
  - restraint
  - packages
  - debug
