---
- include_tasks: repos.yml

- name: Install Restraint client
  package:
    name: "{{ restraint_client_package }}"
    state: latest
  tags:
  - restraint
  - packages

- name: Install Restraint client debugging packages
  package:
    name:
    - "{{ restraint_client_debuginfo_package }}"
    - valgrind
    state: latest
  when: restraint_debug
  tags:
  - restraint
  - packages
  - debug
