---
- name: Include distribution specific variables
  include_vars:
    dir: vars/
    extensions:
    - yml
    - yaml
    ignore_unknown_extensions: yes
    files_matching:
    - "{{ ansible_distribution }}"
  tags:
  - restraint

- name: Setup Restraint YUM repos
  yum_repository:
    file: restraint
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.url }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: no
    skip_if_unavailable: yes
  loop:
    - name: restraint
      description: Restraint Upstream Repo
      url: "{{ restraint_repo_upstream_url }}"
      enabled: yes
    - name: restraint-nightlies
      description: Restraint Nightlies Repo
      url: "{{ restraint_repo_nightlies_url }}"
      enabled: "{{ restraint_repo_nightlies_enabled }}"
  tags:
  - restraint
  - package-repo
  - yum-repo

- name: Install Restraint
  package:
    name:
    - restraint
    - restraint-client
    state: latest
  tags:
  - restraint
  - packages

- name: Install debugging packages
  package:
    name:
    - restraint-debuginfo
    - restraint-client-debuginfo
    - valgrind
    state: latest
  tags:
  - restraint
  - packages
  - debug

- name: Setup Valgrind wrapper
  copy:
    src: restraintd-loves-valgrind.sh
    dest: /usr/local/bin/restraintd-loves-valgrind
    owner: root
    group : root
    mode: '0755'
  tags:
  - resraint
  - debug

- name: Create /root/.ssh directory
  file:
    name: /root/.ssh
    owner: root
    group: root
    state: directory
    mode: '0750'
  tags:
  - restraint
  - ssh

- name: Create root SSH key
  openssh_keypair:
    path: /root/.ssh/id_rsa
  notify:
  - Self authorize root SSH key
  tags:
  - restraint
  - ssh

- name: Create testarea directory
  file:
    name: /testarea
    owner: root
    group: root
    state: directory
    mode: '0755'
  tags:
  - restraint

- name: Copy tasks
  copy:
    src: /vagrant/tasks
    dest: /testarea
    remote_src: yes
  tags:
  - restraint
