---
- include_tasks: repos.yml

- name: Install Restraint server
  package:
    name: "{{ restraint_server_package }}"
    state: latest
  tags:
  - restraint
  - packages

- name: Install Restraint RHTS
  package:
    name: "{{ restraint_server_rhts_package }}"
    state: latest
  when: restraint_rhts
  tags:
  - restraint
  - packages

- name: Install Restraint server debugging packages
  package:
    name:
    - "{{ restraint_server_debuginfo_package }}"
    - valgrind
    state: latest
  when: restraint_debug
  tags:
  - restraint
  - packages
  - debug

- name: Setup Valgrind wrapper
  copy:
    src: restraintd-loves-valgrind.sh
    dest: /usr/local/bin/restraintd-loves-valgrind
    owner: root
    group : root
    mode: '0755'
  when: restraint_debug
  tags:
  - resraint
  - debug
