---
- include_tasks: repos.yml

- name: Install Restraint server
  package:
    name:
    - "restraint{{ restraint_release_tag }}"
    - "restraint-rhts{{ restraint_release_tag }}"
    state: latest
  tags:
  - restraint
  - packages

- name: Install Restraint server debugging packages
  package:
    name:
    - "restraint-debuginfo{{ restraint_release_tag }}"
    - valgrind
    state: latest
  when: restraint_debug
  tags:
  - restraint
  - packages
  - debug

- name: Setup Valgrind wrapper
  copy:
    src: restraintd-loves-valgrind.sh
    dest: /usr/local/bin/restraintd-loves-valgrind
    owner: root
    group : root
    mode: '0755'
  when: restraint_debug
  tags:
  - resraint
  - debug

- name: Create testarea directory
  file:
    name: /testarea
    owner: root
    group: root
    state: directory
    mode: '0755'
  tags:
  - restraint

- name: Copy tasks
  copy:
    src: /vagrant/tasks
    dest: /testarea
    remote_src: yes
  tags:
  - restraint
